# Generated by Django 2.2 on 2021-02-22 08:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210222_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='https://avatars.dicebear.com/4.5/api/male/69.svg', null=True, storage=django.core.files.storage.FileSystemStorage(location='/Volumes/Public/repo/projects/python/django/storages'), upload_to=''),
        ),
    ]
