# Generated by Django 3.1.7 on 2021-02-25 03:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210225_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='https://avatars.dicebear.com/4.5/api/male/52.svg', null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/azmanabdlh/Repositories/django-cookpad/storages'), upload_to=''),
        ),
    ]
